### PR TITLE
test: fix flaky router-luatest/router_2_2_test

### LINKED ISSUE #535: flaky test: router-luatest/router_2_2_test.lua
```
[004] Test failed! Output from reject file /tmp/t/rejects/router-luatest/router_2_2.reject:
[004] Tarantool version is 3.4.0-entrypoint-156-gcdd8bcfbc7
[004] TAP version 13
[004] 1..18
[004] # Started on Thu Mar 13 00:59:46 2025
[004] # Starting group: router
[004] ok     1	router.test_basic
[004] ok     2	router.test_msgpack_args
[004] ok     3	router.test_return_raw
[004] ok     4	router.test_group_buckets
[004] ok     5	router.test_uri_compare_and_reuse
[004] ok     6	router.test_multilisten
[004] ok 7	# SKIP ...ng/tnt/vshard-ee/test/router-luatest/router_2_2_test.lua:338: (no reason specified)
[004] ok     8	router.test_enable_disable
[004] ok     9	router.test_explicit_fiber_kill
[004] ok     10	router.test_simultaneous_cfg
[004] ok     11	router.test_router_service_info
[004] ok     12	router.test_router_box_cfg_mode
[004] not ok 13	router.test_named_config_identification
[004] #   ...Programming/tnt/vshard-ee/test/luatest_helpers/vtest.lua:458: storage reconfig
[004] #   expected: nil, actual: {
[004] #       replica_1_b = ...entian/Programming/tnt/vshard-ee/vshard/storage/init.lua:3914: ...entian/Programming/tnt/vshard-ee/vshard/storage/init.lua:3669: Replicaset name mismatch: already set "cdata<void *>: NULL" but "replicaset_1" in vshard config,
[004] #   }
[004] #   stack traceback:
[004] #   	...Programming/tnt/vshard-ee/test/luatest_helpers/vtest.lua:458: in function 'cluster_cfg'
[004] #   	...ng/tnt/vshard-ee/test/router-luatest/router_2_2_test.lua:615: in function 'router.test_named_config_identification'
[004] #   	...
[004] #   	[C]: in function 'xpcall'
[004] #   artifacts:
[004] #   	replica_1_a -> /tmp/t/004_router-luatest/artifacts/aqcFAB_yNwD-
[004] #   	replica_2_b -> /tmp/t/004_router-luatest/artifacts/grPtJVsUp8bh
[004] #   	replica_2_a -> /tmp/t/004_router-luatest/artifacts/MUyIQwJnl5Zu
[004] ok     14	router.test_master_discovery_on_disconnect
[004] ok     15	router.test_request_timeout
[004] ok     16	router.test_failover_ping_affects_priority
[004] ok     17	router.test_failed_calls_affect_priority
[004] ok     18	router.test_info_with_named_identification
[004] # Ran 17 tests in 39.044 seconds, 16 succeeded, 1 failed, 1 skipped
[004] 
[004] [test-run server "luatest_server"] The log file /tmp/t/004_router-luatest/router_2_2_test.log has zero size
[004] Worker "004_router-luatest" got failed test; restarted the server
```

### PR DESCRIPTION
**Pull request by kamenkremen**
This commit fixes the flakiness of the router_2_2_test. Most failures were caused by low timeouts.

In order to fix this, timeouts are increased, and `t.helpers.retrying` is used in test_replicaset_services_do_not_spam_same_errors and test_log_ratelimiter_is_dropped_on_replica_delete to fix other failures.

Fixes #535

NO_DOC=testfix

### CODE REVIEW

File: test/router-luatest/router_2_2_test.lua [hunk 1]
```diff
@@ -1233,7 +1236,7 @@ g.test_replicaset_services_do_not_spam_same_errors = function(g)
         ivshard.router.internal.static_router.replicasets[uuid].master = nil
     end, {g.replica_2_a:replicaset_uuid()})
     msg = "Error during master search"
-    g.router:wait_log_exactly_once(msg, {timeout = 0.1, on_yield = function()
+    g.router:wait_log_exactly_once(msg, {timeout = 0.5, on_yield = function()
```
Comment (Serpentian) [inline test/router-luatest/router_2_2_test.lua]: How increase of waiting timeout makes the test less flaky? `wait_log_exactly_once` waits for `timeout` seconds and constantly checks the logs, so that the same message doesn't appear. By making timeout greater we just prolong the time of tests and do not make it less flaky

The same comment for all other places

File: test/router-luatest/router_2_2_test.lua [hunk 2]
```diff
@@ -1222,9 +1224,10 @@ g.test_replicaset_services_do_not_spam_same_errors = function(g)
         end
     end)
     local msg = "Ping error from .*replica_2_a"
-    g.router:wait_log_exactly_once(msg, {timeout = 0.1, on_yield = function()
-        _G.failover_wakeup()
-    end})
+    t.helpers.retrying({}, function()
```
Comment (Serpentian) [inline test/router-luatest/router_2_2_test.lua]: We cannot retry here, the whole sense of `wait_log_exactly_once` is that logs are not duplicated. And if it failed once, it'll fail on all iterations, since the whole log after restart of the instance is checked

File: test/router-luatest/router_2_2_test.lua [hunk 3]
```diff
@@ -1181,13 +1183,14 @@ g.test_discovery_not_spam_same_errors = function(g)
...
+    vtest.router_cfg(g.router, global_cfg)
 
     g.router:exec(function(bid)
         ivshard.router._bucket_reset(bid)
         rawset(_G, 'old_interval', ivconst.LOG_RATELIMIT_INTERVAL)
-        ivconst.LOG_RATELIMIT_INTERVAL = 0.1
+        ivconst.LOG_RATELIMIT_INTERVAL = 0.2
     end, {bid})
-    local msg = "Error during discovery .*Peer closed"
+    local msg = "Error during discovery"
```
Comment (Serpentian) [inline test/router-luatest/router_2_2_test.lua]: This makes the test flaky for me:

```
[010] not ok 22	router.test_discovery_not_spam_same_errors
[010] #   ...n/Programming/tnt/vshard/test/luatest_helpers/server.lua:376: Found duplicate 'Error during discovery' in logs
[010] #   expected: "2026-01-13 14:26:01.779 [61054] main/390/vshard.discovery._static_router/vshard.log_ratelimit log_ratelimit.lua:136 W> Error during discovery"
[010] #   actual: "2026-01-13 14:26:01.030 [61054] main/382/vshard.discovery._static_router/vshard.log_ratelimit log_ratelimit.lua:136 W> Error during discovery"
[010] #   stack traceback:
[010] #   	...n/Programming/tnt/vshard/test/luatest_helpers/server.lua:376: in function 'wait_log_exactly_once'
[010] #   	...mming/tnt/vshard/test/router-luatest/router_2_2_test.lua:1194: in function 'router.test_discovery_not_spam_same_errors'
[010] #   artifacts:
[010] #   	replica_2_a -> /tmp/t/010_router-luatest/artifacts/xt3a_YBItQQ0
[010] #   	router -> /tmp/t/010_router-luatest/artifacts/bCT7EtVjjrm5
[010] #   	replica_2_b -> /tmp/t/010_router-luatest/artifacts/rEmDg2jq4oRR
```

File: test/router-luatest/router_2_2_test.lua [hunk 4]
```diff
@@ -1185,9 +1187,9 @@ g.test_discovery_not_spam_same_errors = function(g)
...
```
Comment (Serpentian) [inline test/router-luatest/router_2_2_test.lua]: This makes the test flaky for me:

```
[003] router-luatest/router_2_2_test.lua                                                                                                                                                                             [ fail ]
[003] Test failed! Output from reject file /tmp/t/rejects/router-luatest/router_2_2.reject:
[003] Tarantool version is 3.6.0-entrypoint-132-g49eea0ece5
[003] TAP version 13
[003] 1..25
[003] # Started on Thu Jan 15 18:54:09 2026
[003] # Starting group: router
[003] ok     1	router.test_basic
[003] ok     2	router.test_msgpack_args
[003] ok     3	router.test_return_raw
[003] ok     4	router.test_group_buckets
[003] ok     5	router.test_uri_compare_and_reuse
[003] ok     6	router.test_multilisten
[003] ok     7	router.test_enable_disable
[003] ok     8	router.test_explicit_fiber_kill
[003] ok     9	router.test_simultaneous_cfg
[003] ok     10	router.test_router_service_info
[003] ok     11	router.test_router_box_cfg_mode
[003] ok     12	router.test_named_config_identification
[003] ok     13	router.test_master_discovery_on_disconnect
[003] ok     14	router.test_request_timeout
[003] ok     15	router.test_failover_ping_affects_priority
[003] ok     16	router.test_failed_calls_affect_priority
[003] ok     17	router.test_info_with_named_identification
[003] ok     18	router.test_retryable_transfer_in_progress
[003] ok     19	router.test_discovery_can_be_restarted_fast
[003] ok     20	router.test_cdata_as_bucket_id_is_prohibited
[003] ok     21	router.test_log_ratelimiter_is_dropped_on_replica_delete
[003] not ok 22	router.test_discovery_not_spam_same_errors
[003] #   ...n/Programming/tnt/vshard/test/luatest_helpers/server.lua:376: Found duplicate 'Error during discovery' in logs
[003] #   expected: "2026-01-15 18:54:45.347 [289947] main/391/vshard.discovery._static_router/vshard.log_ratelimit log_ratelimit.lua:136 W> Error during discovery"
[003] #   actual: "2026-01-15 18:54:45.106 [289947] main/383/vshard.discovery._static_router/vshard.log_ratelimit log_ratelimit.lua:136 W> Error during discovery"
[003] #   stack traceback:
[003] #   	...n/Programming/tnt/vshard/test/luatest_helpers/server.lua:376: in function 'wait_log_exactly_once'
[003] #   	...mming/tnt/vshard/test/router-luatest/router_2_2_test.lua:1193: in function 'router.test_discovery_not_spam_same_errors'
[003] #   artifacts:
[003] #   	replica_2_b -> /tmp/t/003_router-luatest/artifacts/4lvC61rXRKjI
[003] #   	router -> /tmp/t/003_router-luatest/artifacts/6XX3gztRYNPO
[003] #   	replica_2_a -> /tmp/t/003_router-luatest/artifacts/DchzJm26xRlB
[003] not ok 23	router.test_replicaset_services_do_not_spam_same_errors
[003] #   ...mming/tnt/vshard/test/router-luatest/router_2_2_test.lua:1217: net_box is not connected
[003] #   stack traceback:
[003] #   	...mming/tnt/vshard/test/router-luatest/router_2_2_test.lua:1217: in function 'router.test_replicaset_services_do_not_spam_same_errors'
[003] ok     24	router.test_log_ratelimiter_is_dropped_on_disable_of_the_service
[003] ok     25	router.test_info_disable_consistency
[003] # Ran 25 tests in 38.770 seconds, 23 succeeded, 1 failed, 1 errored
[003] 
```

**Review by Serpentian — APPROVED** [review]
The test seems stable for me now, thank you!
