### PR TITLE
test: fix flaky router_test

### LINKED ISSUE #403: flaky test: router-luatest/router_test.lua
```
router-luatest/router_test.lua                                  
TAP13 parse failed (Descending test id on line: 'not ok 11\trouter.test_router_service_info').

No result file (router-luatest/router.result) found.
Run the test with --update-result option to write the new result file.
[ fail ]
```

I see no other useful information in logs. [A link to the fail in CI](https://github.com/tarantool/tarantool/actions/runs/4472734416/jobs/7859396051).

### PR DESCRIPTION
**Pull request by Serpentian**
router_test.lua fails constantly on integration CI in tarantool with error 'Peer closed' after simulating unconfigured box. The reason for this problem is very unclear, but the following changes fix it.

Closes #403

NO_DOC=testfix

### CODE REVIEW

File: test/router-luatest/router_test.lua [hunk 1]
```diff
@@ -469,24 +469,23 @@ g.test_enable_disable = function(g)
         _G.fiber_new:set_joinable(true)
     end, {global_cfg})
 
-    -- emulate unconfigured box
-    router:exec(function()
-        rawset(_G, 'old_box_cfg', box.cfg)
+    local err1, err2 = router:exec(function()
+        -- emulate unconfigured box
+        local old_box_cfg = box.cfg
         box.cfg = function(...) return _G.old_box_cfg(...) end
```
Comment (Gerold103) [inline test/router-luatest/router_test.lua:475]: You have to change this line to use `old_box_cfg`, not `_G.old_box_cfg`.

**Review by Gerold103 — CHANGES_REQUESTED** [review]
Thanks for the patch! I couldn't find the reason either. I suspect that luatest somewhere might be trying to do `type(box.cfg)` between execs, or tries to do `box.cfg.<key>`, they fail, and it terminates the connection.

But I couldn't locate any places which could behave like that.

File: test/router-luatest/router_test.lua (hunk 1 above)
Comment (Serpentian) [reply test/router-luatest/router_test.lua]: My bad( Fixed
